# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addofficialui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addOfficialDialog(object):
    def setupUi(self, addOfficialDialog):
        addOfficialDialog.setObjectName("addOfficialDialog")
        addOfficialDialog.resize(1057, 912)
        addOfficialDialog.setStyleSheet("background-color: rgb(229,228,226);")
        self.frame = QtWidgets.QFrame(addOfficialDialog)
        self.frame.setGeometry(QtCore.QRect(29, 29, 1001, 861))
        self.frame.setStyleSheet("background-color: rgb(242,243,244);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.addofficial_cancel_button = QtWidgets.QPushButton(self.frame)
        self.addofficial_cancel_button.setGeometry(QtCore.QRect(540, 800, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addofficial_cancel_button.setFont(font)
        self.addofficial_cancel_button.setStyleSheet("background-color: white;\n"
"border: 2px solid grey;\n"
"border-radius: 13px;")
        self.addofficial_cancel_button.setObjectName("addofficial_cancel_button")
        self.addofficial_save_button = QtWidgets.QPushButton(self.frame)
        self.addofficial_save_button.setGeometry(QtCore.QRect(360, 800, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addofficial_save_button.setFont(font)
        self.addofficial_save_button.setStyleSheet("background-color: white;\n"
"border: 2px solid grey;\n"
"border-radius: 13px;")
        self.addofficial_save_button.setObjectName("addofficial_save_button")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 1401, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.label_8.setObjectName("label_8")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(40, 130, 921, 651))
        self.frame_2.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 13px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_resident_id = QtWidgets.QLabel(self.frame_2)
        self.label_resident_id.setGeometry(QtCore.QRect(70, 60, 211, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resident_id.setFont(font)
        self.label_resident_id.setStyleSheet("border: 0px")
        self.label_resident_id.setObjectName("label_resident_id")
        self.label_first_name = QtWidgets.QLabel(self.frame_2)
        self.label_first_name.setGeometry(QtCore.QRect(70, 126, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_first_name.setFont(font)
        self.label_first_name.setStyleSheet("border: 0px")
        self.label_first_name.setObjectName("label_first_name")
        self.addofficial_officialID_input = QtWidgets.QLineEdit(self.frame_2)
        self.addofficial_officialID_input.setGeometry(QtCore.QRect(70, 91, 311, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addofficial_officialID_input.setFont(font)
        self.addofficial_officialID_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 13px;")
        self.addofficial_officialID_input.setObjectName("addofficial_officialID_input")
        self.addofficial_position_box = QtWidgets.QComboBox(self.frame_2)
        self.addofficial_position_box.setGeometry(QtCore.QRect(70, 160, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addofficial_position_box.setFont(font)
        self.addofficial_position_box.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 13px;")
        self.addofficial_position_box.setObjectName("addofficial_position_box")
        self.addofficial_firstname_input = QtWidgets.QLineEdit(self.frame_2)
        self.addofficial_firstname_input.setGeometry(QtCore.QRect(70, 254, 311, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addofficial_firstname_input.setFont(font)
        self.addofficial_firstname_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 13px;")
        self.addofficial_firstname_input.setObjectName("addofficial_firstname_input")
        self.addofficial_contact_input = QtWidgets.QLineEdit(self.frame_2)
        self.addofficial_contact_input.setGeometry(QtCore.QRect(70, 410, 311, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addofficial_contact_input.setFont(font)
        self.addofficial_contact_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 13px;")
        self.addofficial_contact_input.setObjectName("addofficial_contact_input")
        self.addofficial_lastname_input = QtWidgets.QLineEdit(self.frame_2)
        self.addofficial_lastname_input.setGeometry(QtCore.QRect(70, 320, 311, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addofficial_lastname_input.setFont(font)
        self.addofficial_lastname_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 13px;")
        self.addofficial_lastname_input.setObjectName("addofficial_lastname_input")
        self.label_last_name = QtWidgets.QLabel(self.frame_2)
        self.label_last_name.setGeometry(QtCore.QRect(70, 289, 121, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_last_name.setFont(font)
        self.label_last_name.setStyleSheet("border: 0px")
        self.label_last_name.setObjectName("label_last_name")
        self.label_first_name_2 = QtWidgets.QLabel(self.frame_2)
        self.label_first_name_2.setGeometry(QtCore.QRect(70, 223, 111, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_first_name_2.setFont(font)
        self.label_first_name_2.setStyleSheet("border: 0px")
        self.label_first_name_2.setObjectName("label_first_name_2")
        self.label_contact = QtWidgets.QLabel(self.frame_2)
        self.label_contact.setGeometry(QtCore.QRect(70, 379, 91, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_contact.setFont(font)
        self.label_contact.setStyleSheet("border: 0px")
        self.label_contact.setObjectName("label_contact")

        self.retranslateUi(addOfficialDialog)
        QtCore.QMetaObject.connectSlotsByName(addOfficialDialog)

    def retranslateUi(self, addOfficialDialog):
        _translate = QtCore.QCoreApplication.translate
        addOfficialDialog.setWindowTitle(_translate("addOfficialDialog", "Add New Official"))
        self.addofficial_cancel_button.setText(_translate("addOfficialDialog", "Cancel"))
        self.addofficial_save_button.setText(_translate("addOfficialDialog", "Add"))
        self.label_8.setText(_translate("addOfficialDialog", "  Add Officials"))
        self.label_resident_id.setText(_translate("addOfficialDialog", "Official ID:"))
        self.label_first_name.setText(_translate("addOfficialDialog", "Position:"))
        self.label_last_name.setText(_translate("addOfficialDialog", "Last Name:"))
        self.label_first_name_2.setText(_translate("addOfficialDialog", "First Name:"))
        self.label_contact.setText(_translate("addOfficialDialog", "Contact:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addOfficialDialog = QtWidgets.QDialog()
    ui = Ui_addOfficialDialog()
    ui.setupUi(addOfficialDialog)
    addOfficialDialog.show()
    sys.exit(app.exec_())
