# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QGraphicsDropShadowEffect
from PyQt5.QtGui import QColor
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1580, 792)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fullMenu = QtWidgets.QWidget(self.centralwidget)
        self.fullMenu.setGeometry(QtCore.QRect(10, 10, 241, 771))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fullMenu.setFont(font)
        self.fullMenu.setStyleSheet("background-color: rgb(0, 0, 25);\n"
"border-radius: 13px;\n"
"color: white;")
        self.fullMenu.setObjectName("fullMenu")
        self.homeBtn = QtWidgets.QPushButton(self.fullMenu)
        self.homeBtn.setGeometry(QtCore.QRect(10, 170, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.homeBtn.setFont(font)
        self.homeBtn.setStyleSheet("background-color: rgb(0, 0, 30);\n"
"border-radius: 13px;\n"
"text-align: left;\n"
"color: white;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon)
        self.homeBtn.setObjectName("homeBtn")
        self.resBtn = QtWidgets.QPushButton(self.fullMenu)
        self.resBtn.setGeometry(QtCore.QRect(10, 220, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.resBtn.setFont(font)
        self.resBtn.setStyleSheet("background-color: rgb(0, 0, 30);\n"
"border-radius: 13px;\n"
"text-align: left;\n"
"color: white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/users-alt.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resBtn.setIcon(icon1)
        self.resBtn.setObjectName("resBtn")
        self.compBtn = QtWidgets.QPushButton(self.fullMenu)
        self.compBtn.setGeometry(QtCore.QRect(10, 270, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.compBtn.setFont(font)
        self.compBtn.setStyleSheet("background-color: rgb(0, 0, 30);\n"
"border-radius: 13px;\n"
"text-align: left;\n"
"color: white;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/document.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.compBtn.setIcon(icon2)
        self.compBtn.setObjectName("compBtn")
        self.offiBtn = QtWidgets.QPushButton(self.fullMenu)
        self.offiBtn.setGeometry(QtCore.QRect(10, 320, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.offiBtn.setFont(font)
        self.offiBtn.setStyleSheet("background-color: rgb(0, 0, 30);\n"
"border-radius: 13px;\n"
"text-align: left;\n"
"color: white;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/briefcase.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offiBtn.setIcon(icon3)
        self.offiBtn.setObjectName("offiBtn")
        self.exBtn = QtWidgets.QPushButton(self.fullMenu)
        self.exBtn.setGeometry(QtCore.QRect(10, 580, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.exBtn.setFont(font)
        self.exBtn.setStyleSheet("background-color: rgb(0, 0, 30);\n"
"border-radius: 13px;\n"
"text-align: left;\n"
"color: white;")
        self.exBtn.setObjectName("exBtn")
        self.abtBtn = QtWidgets.QPushButton(self.fullMenu)
        self.abtBtn.setGeometry(QtCore.QRect(10, 370, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.abtBtn.setFont(font)
        self.abtBtn.setStyleSheet("background-color: rgb(0, 0, 30);\n"
"border-radius: 13px;\n"
"text-align: left;\n"
"color: white;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/interrogation.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abtBtn.setIcon(icon4)
        self.abtBtn.setObjectName("abtBtn")
        self.frame = QtWidgets.QFrame(self.fullMenu)
        self.frame.setGeometry(QtCore.QRect(-10, -11, 261, 101))
        self.frame.setStyleSheet("border: 1px solid rgb(230, 230, 230);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 241, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(27)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-radius: 0px;\n"
"border: 0px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.fullMenu)
        self.label_4.setGeometry(QtCore.QRect(0, 140, 241, 20))
        self.label_4.setStyleSheet("color: grey;")
        self.label_4.setObjectName("label_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(260, 10, 1311, 771))
        self.stackedWidget.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-radius: 13px;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1311, 91))
        self.frame_2.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0px;")
        self.label.setObjectName("label")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(30, 100, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.frame_7 = QtWidgets.QFrame(self.page)
        self.frame_7.setGeometry(QtCore.QRect(30, 190, 171, 81))
        self.frame_7.setStyleSheet("background-color: rgb(255, 217, 148);\n"
"border-radius: 13px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.pendingComp_line = QtWidgets.QLineEdit(self.frame_7)
        self.pendingComp_line.setGeometry(QtCore.QRect(0, 30, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pendingComp_line.setFont(font)
        self.pendingComp_line.setAlignment(QtCore.Qt.AlignCenter)
        self.pendingComp_line.setObjectName("pendingComp_line")
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(0, -1, 161, 31))
        self.label_11.setObjectName("label_11")
        self.frame_8 = QtWidgets.QFrame(self.page)
        self.frame_8.setGeometry(QtCore.QRect(210, 190, 171, 81))
        self.frame_8.setStyleSheet("background-color: rgb(255, 179, 179);\n"
"border-radius: 13px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.totalComp_line = QtWidgets.QLineEdit(self.frame_8)
        self.totalComp_line.setGeometry(QtCore.QRect(0, 30, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.totalComp_line.setFont(font)
        self.totalComp_line.setAlignment(QtCore.Qt.AlignCenter)
        self.totalComp_line.setObjectName("totalComp_line")
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 161, 31))
        self.label_12.setObjectName("label_12")
        self.frame_9 = QtWidgets.QFrame(self.page)
        self.frame_9.setGeometry(QtCore.QRect(390, 190, 171, 81))
        self.frame_9.setStyleSheet("background-color: rgb(148, 255, 148);\n"
"border-radius: 13px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_7.setGeometry(QtCore.QRect(140, 140, 401, 71))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.completeComp_line = QtWidgets.QLineEdit(self.frame_9)
        self.completeComp_line.setGeometry(QtCore.QRect(0, 30, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.completeComp_line.setFont(font)
        self.completeComp_line.setAlignment(QtCore.Qt.AlignCenter)
        self.completeComp_line.setObjectName("completeComp_line")
        self.label_13 = QtWidgets.QLabel(self.frame_9)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 161, 31))
        self.label_13.setObjectName("label_13")
        self.frame_10 = QtWidgets.QFrame(self.page)
        self.frame_10.setGeometry(QtCore.QRect(570, 190, 171, 81))
        self.frame_10.setStyleSheet("background-color: rgb(184, 184, 255);\n"
"border-radius: 13px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.totalOffi_line = QtWidgets.QLineEdit(self.frame_10)
        self.totalOffi_line.setGeometry(QtCore.QRect(0, 30, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.totalOffi_line.setFont(font)
        self.totalOffi_line.setText("")
        self.totalOffi_line.setAlignment(QtCore.Qt.AlignCenter)
        self.totalOffi_line.setObjectName("totalOffi_line")
        self.label_14 = QtWidgets.QLabel(self.frame_10)
        self.label_14.setGeometry(QtCore.QRect(0, 0, 161, 31))
        self.label_14.setObjectName("label_14")
        self.frame_11 = QtWidgets.QFrame(self.page)
        self.frame_11.setGeometry(QtCore.QRect(750, 190, 171, 81))
        self.frame_11.setStyleSheet("background-color: rgb(255, 255, 171);\n"
"border-radius: 13px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.totalRes_line = QtWidgets.QLineEdit(self.frame_11)
        self.totalRes_line.setGeometry(QtCore.QRect(0, 30, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.totalRes_line.setFont(font)
        self.totalRes_line.setAlignment(QtCore.Qt.AlignCenter)
        self.totalRes_line.setObjectName("totalRes_line")
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 161, 31))
        self.label_15.setObjectName("label_15")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(30, 140, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: grey;")
        self.label_9.setObjectName("label_9")
        self.labelDateTime1 = QtWidgets.QLabel(self.page)
        self.labelDateTime1.setGeometry(QtCore.QRect(1070, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDateTime1.setFont(font)
        self.labelDateTime1.setStyleSheet("border: 0px;\n"
"background-color: white;")
        self.labelDateTime1.setObjectName("labelDateTime1")
        self.frame_12 = QtWidgets.QFrame(self.page)
        self.frame_12.setGeometry(QtCore.QRect(950, 190, 341, 201))
        self.frame_12.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.frame_12)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 10, 321, 181))
        self.calendarWidget.setStyleSheet("border: 0px;\n"
"color: black;\n"
"\n"
"QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    font-size: 7;\n"
"}\n"
"")
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.ISOWeekNumbers)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.frame_13 = QtWidgets.QFrame(self.page)
        self.frame_13.setGeometry(QtCore.QRect(20, 280, 911, 471))
        self.frame_13.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.pendingComp_table = QtWidgets.QTableWidget(self.frame_13)
        self.pendingComp_table.setGeometry(QtCore.QRect(10, 70, 871, 371))
        self.pendingComp_table.setStyleSheet("background-color: white;\n"
"border: 0px;\n"
"border-radius: 0px;")
        self.pendingComp_table.setObjectName("pendingComp_table")
        self.pendingComp_table.setColumnCount(5)
        self.pendingComp_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.pendingComp_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pendingComp_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pendingComp_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.pendingComp_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.pendingComp_table.setHorizontalHeaderItem(4, item)
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: 0px;")
        self.label_10.setObjectName("label_10")
        self.filter_line = QtWidgets.QLineEdit(self.frame_13)
        self.filter_line.setGeometry(QtCore.QRect(470, 10, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filter_line.setFont(font)
        self.filter_line.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.filter_line.setObjectName("filter_line")
        self.refreshPendCompBtn = QtWidgets.QPushButton(self.frame_13)
        self.refreshPendCompBtn.setGeometry(QtCore.QRect(790, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.refreshPendCompBtn.setFont(font)
        self.refreshPendCompBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.refreshPendCompBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshPendCompBtn.setIcon(icon5)
        self.refreshPendCompBtn.setObjectName("refreshPendCompBtn")
        self.filterPendCompBtn = QtWidgets.QPushButton(self.frame_13)
        self.filterPendCompBtn.setGeometry(QtCore.QRect(840, 20, 41, 31))
        self.filterPendCompBtn.setStyleSheet("background-color: white;\n"
"border-radius: 9px;")
        self.filterPendCompBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterPendCompBtn.setIcon(icon6)
        self.filterPendCompBtn.setObjectName("filterPendCompBtn")
        self.filterPendComp_box = QtWidgets.QComboBox(self.frame_13)
        self.filterPendComp_box.setGeometry(QtCore.QRect(330, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filterPendComp_box.setFont(font)
        self.filterPendComp_box.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);")
        self.filterPendComp_box.setObjectName("filterPendComp_box")
        self.filterPendComp_box.addItem("")
        self.filterPendComp_box.addItem("")
        self.filterPendComp_box.addItem("")
        self.filterPendComp_box.addItem("")
        self.filterPendComp_box.addItem("")
        self.filterPendComp_box.addItem("")
        self.frame_14 = QtWidgets.QFrame(self.page)
        self.frame_14.setGeometry(QtCore.QRect(950, 400, 341, 351))
        self.frame_14.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.sortCases_box = QtWidgets.QComboBox(self.page)
        self.sortCases_box.setGeometry(QtCore.QRect(1010, 120, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sortCases_box.setFont(font)
        self.sortCases_box.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);")
        self.sortCases_box.setObjectName("sortCases_box")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.sortCases_box.addItem("")
        self.refreshCasesBtn = QtWidgets.QPushButton(self.page)
        self.refreshCasesBtn.setGeometry(QtCore.QRect(1130, 120, 111, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.refreshCasesBtn.setFont(font)
        self.refreshCasesBtn.setStyleSheet("background-color: blue;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: white;")
        self.refreshCasesBtn.setObjectName("refreshCasesBtn")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_3 = QtWidgets.QFrame(self.page_3)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1311, 91))
        self.frame_3.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 0px;")
        self.label_2.setObjectName("label_2")
        self.searchResBtn = QtWidgets.QPushButton(self.frame_3)
        self.searchResBtn.setGeometry(QtCore.QRect(1230, 30, 41, 31))
        self.searchResBtn.setStyleSheet("background-color: white;\n"
"border-radius: 9px;")
        self.searchResBtn.setText("")
        self.searchResBtn.setIcon(icon6)
        self.searchResBtn.setObjectName("searchResBtn")
        self.searchRes_line = QtWidgets.QLineEdit(self.frame_3)
        self.searchRes_line.setGeometry(QtCore.QRect(860, 20, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchRes_line.setFont(font)
        self.searchRes_line.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.searchRes_line.setObjectName("searchRes_line")
        self.refreshResBtn = QtWidgets.QPushButton(self.frame_3)
        self.refreshResBtn.setGeometry(QtCore.QRect(1180, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.refreshResBtn.setFont(font)
        self.refreshResBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.refreshResBtn.setText("")
        self.refreshResBtn.setIcon(icon5)
        self.refreshResBtn.setObjectName("refreshResBtn")
        self.searchbyRes_box = QtWidgets.QComboBox(self.frame_3)
        self.searchbyRes_box.setGeometry(QtCore.QRect(710, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchbyRes_box.setFont(font)
        self.searchbyRes_box.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.searchbyRes_box.setObjectName("searchbyRes_box")
        self.searchbyRes_box.addItem("")
        self.searchbyRes_box.addItem("")
        self.searchbyRes_box.addItem("")
        self.searchbyRes_box.addItem("")
        self.searchbyRes_box.addItem("")
        self.searchbyRes_box.addItem("")
        self.searchbyRes_box.addItem("")
        self.label_2.raise_()
        self.searchRes_line.raise_()
        self.searchResBtn.raise_()
        self.refreshResBtn.raise_()
        self.searchbyRes_box.raise_()
        self.resident_table = QtWidgets.QTableWidget(self.page_3)
        self.resident_table.setGeometry(QtCore.QRect(30, 160, 1251, 551))
        self.resident_table.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);\n"
"border-radius: 0px;")
        self.resident_table.setObjectName("resident_table")
        self.resident_table.setColumnCount(6)
        self.resident_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(5, item)
        self.resident_table.horizontalHeader().setStretchLastSection(False)
        self.addResBtn = QtWidgets.QPushButton(self.page_3)
        self.addResBtn.setGeometry(QtCore.QRect(1110, 110, 161, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.addResBtn.setFont(font)
        self.addResBtn.setStyleSheet("background-color: blue;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: white;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addResBtn.setIcon(icon7)
        self.addResBtn.setObjectName("addResBtn")
        self.sortRes_box = QtWidgets.QComboBox(self.page_3)
        self.sortRes_box.setGeometry(QtCore.QRect(40, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sortRes_box.setFont(font)
        self.sortRes_box.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.sortRes_box.setObjectName("sortRes_box")
        self.sortRes_box.addItem("")
        self.sortRes_box.addItem("")
        self.sortRes_box.addItem("")
        self.sortRes_box.addItem("")
        self.sortRes_box.addItem("")
        self.sortRes_box.addItem("")
        self.sortRes_box.addItem("")
        self.refreshResBtn_2 = QtWidgets.QPushButton(self.page_3)
        self.refreshResBtn_2.setGeometry(QtCore.QRect(180, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.refreshResBtn_2.setFont(font)
        self.refreshResBtn_2.setStyleSheet("background-color: rgb(255, 255, 171);\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: black;")
        self.refreshResBtn_2.setObjectName("refreshResBtn_2")
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(590, 720, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.pushButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/angle-double-left.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon8)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 720, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.pushButton_2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/angle-double-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon9)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(640, 717, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_4 = QtWidgets.QFrame(self.page_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1311, 91))
        self.frame_4.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 0px;")
        self.label_5.setObjectName("label_5")
        self.searchComp_line = QtWidgets.QLineEdit(self.frame_4)
        self.searchComp_line.setGeometry(QtCore.QRect(860, 20, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchComp_line.setFont(font)
        self.searchComp_line.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.searchComp_line.setObjectName("searchComp_line")
        self.searchCompBtn = QtWidgets.QPushButton(self.frame_4)
        self.searchCompBtn.setGeometry(QtCore.QRect(1230, 30, 41, 31))
        self.searchCompBtn.setStyleSheet("background-color: white;\n"
"border-radius: 9px;")
        self.searchCompBtn.setText("")
        self.searchCompBtn.setIcon(icon6)
        self.searchCompBtn.setObjectName("searchCompBtn")
        self.refreshCompBtn = QtWidgets.QPushButton(self.frame_4)
        self.refreshCompBtn.setGeometry(QtCore.QRect(1180, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.refreshCompBtn.setFont(font)
        self.refreshCompBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.refreshCompBtn.setText("")
        self.refreshCompBtn.setIcon(icon5)
        self.refreshCompBtn.setObjectName("refreshCompBtn")
        self.searchbyComp_box = QtWidgets.QComboBox(self.frame_4)
        self.searchbyComp_box.setGeometry(QtCore.QRect(710, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchbyComp_box.setFont(font)
        self.searchbyComp_box.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.searchbyComp_box.setObjectName("searchbyComp_box")
        self.searchbyComp_box.addItem("")
        self.searchbyComp_box.addItem("")
        self.searchbyComp_box.addItem("")
        self.searchbyComp_box.addItem("")
        self.searchbyComp_box.addItem("")
        self.searchbyComp_box.addItem("")
        self.complaint_table = QtWidgets.QTableWidget(self.page_2)
        self.complaint_table.setGeometry(QtCore.QRect(30, 160, 1251, 551))
        self.complaint_table.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);\n"
"border-radius: 0px;")
        self.complaint_table.setObjectName("complaint_table")
        self.complaint_table.setColumnCount(5)
        self.complaint_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(4, item)
        self.addCompBtn = QtWidgets.QPushButton(self.page_2)
        self.addCompBtn.setGeometry(QtCore.QRect(1110, 110, 161, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.addCompBtn.setFont(font)
        self.addCompBtn.setStyleSheet("background-color: blue;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: white;")
        self.addCompBtn.setIcon(icon7)
        self.addCompBtn.setObjectName("addCompBtn")
        self.sortComp_box = QtWidgets.QComboBox(self.page_2)
        self.sortComp_box.setGeometry(QtCore.QRect(40, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sortComp_box.setFont(font)
        self.sortComp_box.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.sortComp_box.setObjectName("sortComp_box")
        self.sortComp_box.addItem("")
        self.sortComp_box.addItem("")
        self.sortComp_box.addItem("")
        self.sortComp_box.addItem("")
        self.sortComp_box.addItem("")
        self.sortComp_box.addItem("")
        self.refreshCompBtn_2 = QtWidgets.QPushButton(self.page_2)
        self.refreshCompBtn_2.setGeometry(QtCore.QRect(180, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.refreshCompBtn_2.setFont(font)
        self.refreshCompBtn_2.setStyleSheet("background-color: rgb(255, 255, 171);\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: black;")
        self.refreshCompBtn_2.setObjectName("refreshCompBtn_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 720, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon8)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(640, 717, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_4.setGeometry(QtCore.QRect(700, 720, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon9)
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_5 = QtWidgets.QFrame(self.page_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1311, 91))
        self.frame_5.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: 0px;")
        self.label_6.setObjectName("label_6")
        self.searchOffi_line = QtWidgets.QLineEdit(self.frame_5)
        self.searchOffi_line.setGeometry(QtCore.QRect(860, 20, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchOffi_line.setFont(font)
        self.searchOffi_line.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.searchOffi_line.setObjectName("searchOffi_line")
        self.searchOffiBtn = QtWidgets.QPushButton(self.frame_5)
        self.searchOffiBtn.setGeometry(QtCore.QRect(1230, 30, 41, 31))
        self.searchOffiBtn.setStyleSheet("background-color: white;\n"
"border-radius: 9px;")
        self.searchOffiBtn.setText("")
        self.searchOffiBtn.setIcon(icon6)
        self.searchOffiBtn.setObjectName("searchOffiBtn")
        self.refreshOffiBtn = QtWidgets.QPushButton(self.frame_5)
        self.refreshOffiBtn.setGeometry(QtCore.QRect(1180, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.refreshOffiBtn.setFont(font)
        self.refreshOffiBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.refreshOffiBtn.setText("")
        self.refreshOffiBtn.setIcon(icon5)
        self.refreshOffiBtn.setObjectName("refreshOffiBtn")
        self.searchbyOff_box = QtWidgets.QComboBox(self.frame_5)
        self.searchbyOff_box.setGeometry(QtCore.QRect(710, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchbyOff_box.setFont(font)
        self.searchbyOff_box.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.searchbyOff_box.setObjectName("searchbyOff_box")
        self.searchbyOff_box.addItem("")
        self.searchbyOff_box.addItem("")
        self.searchbyOff_box.addItem("")
        self.searchbyOff_box.addItem("")
        self.searchbyOff_box.addItem("")
        self.searchbyOff_box.addItem("")
        self.label_6.raise_()
        self.searchOffi_line.raise_()
        self.searchbyOff_box.raise_()
        self.refreshOffiBtn.raise_()
        self.searchOffiBtn.raise_()
        self.official_table = QtWidgets.QTableWidget(self.page_4)
        self.official_table.setGeometry(QtCore.QRect(30, 160, 1251, 551))
        self.official_table.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);\n"
"border-radius: 0px;")
        self.official_table.setObjectName("official_table")
        self.official_table.setColumnCount(5)
        self.official_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.official_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.official_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.official_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.official_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.official_table.setHorizontalHeaderItem(4, item)
        self.addOffiBtn = QtWidgets.QPushButton(self.page_4)
        self.addOffiBtn.setGeometry(QtCore.QRect(1110, 110, 161, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.addOffiBtn.setFont(font)
        self.addOffiBtn.setStyleSheet("background-color: blue;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: white;")
        self.addOffiBtn.setIcon(icon7)
        self.addOffiBtn.setObjectName("addOffiBtn")
        self.sortOff_box = QtWidgets.QComboBox(self.page_4)
        self.sortOff_box.setGeometry(QtCore.QRect(40, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sortOff_box.setFont(font)
        self.sortOff_box.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.sortOff_box.setObjectName("sortOff_box")
        self.sortOff_box.addItem("")
        self.sortOff_box.addItem("")
        self.sortOff_box.addItem("")
        self.sortOff_box.addItem("")
        self.sortOff_box.addItem("")
        self.sortOff_box.addItem("")
        self.refreshOffiBtn_2 = QtWidgets.QPushButton(self.page_4)
        self.refreshOffiBtn_2.setGeometry(QtCore.QRect(180, 110, 111, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.refreshOffiBtn_2.setFont(font)
        self.refreshOffiBtn_2.setStyleSheet("background-color: rgb(255, 255, 171);\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: black;")
        self.refreshOffiBtn_2.setObjectName("refreshOffiBtn_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(640, 717, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_5.setGeometry(QtCore.QRect(700, 720, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon9)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_6.setGeometry(QtCore.QRect(590, 720, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon8)
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.frame_6 = QtWidgets.QFrame(self.page_5)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 1311, 91))
        self.frame_6.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(16, 10, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: 0px;")
        self.label_7.setObjectName("label_7")
        self.labelDateTime2 = QtWidgets.QLabel(self.frame_6)
        self.labelDateTime2.setGeometry(QtCore.QRect(1070, 30, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDateTime2.setFont(font)
        self.labelDateTime2.setStyleSheet("border: 0px;")
        self.labelDateTime2.setObjectName("labelDateTime2")
        self.stackedWidget.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeBtn.setText(_translate("MainWindow", "Dashboard"))
        self.resBtn.setText(_translate("MainWindow", "Residents"))
        self.compBtn.setText(_translate("MainWindow", "Complaints"))
        self.offiBtn.setText(_translate("MainWindow", "Officials"))
        self.exBtn.setText(_translate("MainWindow", "Exit"))
        self.abtBtn.setText(_translate("MainWindow", "About"))
        self.label_3.setText(_translate("MainWindow", "ComplaSys"))
        self.label_4.setText(_translate("MainWindow", "   Case Management"))
        self.label.setText(_translate("MainWindow", "Dashboard"))
        self.label_8.setText(_translate("MainWindow", "Welcome back, Admin!"))
        self.label_11.setText(_translate("MainWindow", "  Pending Cases"))
        self.label_12.setText(_translate("MainWindow", "  Cancelled Cases:"))
        self.label_13.setText(_translate("MainWindow", "  Completed Cases:"))
        self.label_14.setText(_translate("MainWindow", "  Total Officials:"))
        self.label_15.setText(_translate("MainWindow", "  Total Residents:"))
        self.label_9.setText(_translate("MainWindow", "Let\'s make today efficient and resident-friendly."))
        self.labelDateTime1.setText(_translate("MainWindow", "TextLabel"))
        item = self.pendingComp_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COMPLAINTID"))
        item = self.pendingComp_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CATEGORY"))
        item = self.pendingComp_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DATETIME"))
        item = self.pendingComp_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LOCATION"))
        item = self.pendingComp_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "STATUS"))
        self.label_10.setText(_translate("MainWindow", "Pending Cases"))
        self.filter_line.setPlaceholderText(_translate("MainWindow", "  Filter"))
        self.filterPendComp_box.setItemText(0, _translate("MainWindow", " FILTER"))
        self.filterPendComp_box.setItemText(1, _translate("MainWindow", "COMPLAINTID"))
        self.filterPendComp_box.setItemText(2, _translate("MainWindow", "CATEGORY"))
        self.filterPendComp_box.setItemText(3, _translate("MainWindow", "DATETIME"))
        self.filterPendComp_box.setItemText(4, _translate("MainWindow", "LOCATION"))
        self.filterPendComp_box.setItemText(5, _translate("MainWindow", "STATUS"))
        self.sortCases_box.setItemText(0, _translate("MainWindow", "Month"))
        self.sortCases_box.setItemText(1, _translate("MainWindow", "January"))
        self.sortCases_box.setItemText(2, _translate("MainWindow", "Februrary"))
        self.sortCases_box.setItemText(3, _translate("MainWindow", "March"))
        self.sortCases_box.setItemText(4, _translate("MainWindow", "April"))
        self.sortCases_box.setItemText(5, _translate("MainWindow", "May"))
        self.sortCases_box.setItemText(6, _translate("MainWindow", "June"))
        self.sortCases_box.setItemText(7, _translate("MainWindow", "July"))
        self.sortCases_box.setItemText(8, _translate("MainWindow", "August"))
        self.sortCases_box.setItemText(9, _translate("MainWindow", "September"))
        self.sortCases_box.setItemText(10, _translate("MainWindow", "October"))
        self.sortCases_box.setItemText(11, _translate("MainWindow", "December"))
        self.refreshCasesBtn.setText(_translate("MainWindow", "Refresh"))
        self.label_2.setText(_translate("MainWindow", "Residents"))
        self.searchRes_line.setPlaceholderText(_translate("MainWindow", "    Search Residents..."))
        self.searchbyRes_box.setItemText(0, _translate("MainWindow", " SEARCH BY"))
        self.searchbyRes_box.setItemText(1, _translate("MainWindow", " RESIDENTID"))
        self.searchbyRes_box.setItemText(2, _translate("MainWindow", " FIRSTNAME"))
        self.searchbyRes_box.setItemText(3, _translate("MainWindow", " LASTNAME"))
        self.searchbyRes_box.setItemText(4, _translate("MainWindow", " AGE"))
        self.searchbyRes_box.setItemText(5, _translate("MainWindow", " SEX"))
        self.searchbyRes_box.setItemText(6, _translate("MainWindow", " CONTACT"))
        item = self.resident_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "RESIDENTID"))
        item = self.resident_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FIRSTNAME"))
        item = self.resident_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "LASTNAME"))
        item = self.resident_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AGE"))
        item = self.resident_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SEX"))
        item = self.resident_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "CONTACT"))
        self.addResBtn.setText(_translate("MainWindow", "Add Resident"))
        self.sortRes_box.setItemText(0, _translate("MainWindow", " SORT"))
        self.sortRes_box.setItemText(1, _translate("MainWindow", " RESIDENTID"))
        self.sortRes_box.setItemText(2, _translate("MainWindow", " FIRSTNAME"))
        self.sortRes_box.setItemText(3, _translate("MainWindow", " LASTNAME"))
        self.sortRes_box.setItemText(4, _translate("MainWindow", " AGE"))
        self.sortRes_box.setItemText(5, _translate("MainWindow", " SEX"))
        self.sortRes_box.setItemText(6, _translate("MainWindow", " CONTACT"))
        self.refreshResBtn_2.setText(_translate("MainWindow", "Refresh"))
        self.lineEdit_2.setText(_translate("MainWindow", "32"))
        self.label_5.setText(_translate("MainWindow", "Complaints"))
        self.searchComp_line.setPlaceholderText(_translate("MainWindow", "    Search Complaints..."))
        self.searchbyComp_box.setItemText(0, _translate("MainWindow", " SEARCH BY"))
        self.searchbyComp_box.setItemText(1, _translate("MainWindow", "COMPLAINTID"))
        self.searchbyComp_box.setItemText(2, _translate("MainWindow", "RESIDENTID"))
        self.searchbyComp_box.setItemText(3, _translate("MainWindow", "CATEGORY"))
        self.searchbyComp_box.setItemText(4, _translate("MainWindow", "DATETIME"))
        self.searchbyComp_box.setItemText(5, _translate("MainWindow", "STATUS"))
        item = self.complaint_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COMPLAINTID"))
        item = self.complaint_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "RESIDENTID"))
        item = self.complaint_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CATEGORY"))
        item = self.complaint_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "DATETIME"))
        item = self.complaint_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "STATUS"))
        self.addCompBtn.setText(_translate("MainWindow", "Add Complaint"))
        self.sortComp_box.setItemText(0, _translate("MainWindow", " SORT"))
        self.sortComp_box.setItemText(1, _translate("MainWindow", "COMPLAINTID"))
        self.sortComp_box.setItemText(2, _translate("MainWindow", "RESIDENTID"))
        self.sortComp_box.setItemText(3, _translate("MainWindow", "CATEGORY"))
        self.sortComp_box.setItemText(4, _translate("MainWindow", "DATETIME"))
        self.sortComp_box.setItemText(5, _translate("MainWindow", "STATUS"))
        self.refreshCompBtn_2.setText(_translate("MainWindow", "Refresh"))
        self.lineEdit_3.setText(_translate("MainWindow", "32"))
        self.label_6.setText(_translate("MainWindow", "Officials"))
        self.searchOffi_line.setPlaceholderText(_translate("MainWindow", "    Search Officials..."))
        self.searchbyOff_box.setItemText(0, _translate("MainWindow", " SEARCH BY"))
        self.searchbyOff_box.setItemText(1, _translate("MainWindow", " OFFICIALID"))
        self.searchbyOff_box.setItemText(2, _translate("MainWindow", " POSITION"))
        self.searchbyOff_box.setItemText(3, _translate("MainWindow", " FIRSTNAME"))
        self.searchbyOff_box.setItemText(4, _translate("MainWindow", " LASTNAME"))
        self.searchbyOff_box.setItemText(5, _translate("MainWindow", " CONTACT"))
        item = self.official_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "OFFICIALID"))
        item = self.official_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "POSITION"))
        item = self.official_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FIRSTNAME"))
        item = self.official_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LASTNAME"))
        item = self.official_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CONTACT"))
        self.addOffiBtn.setText(_translate("MainWindow", "Add Official"))
        self.sortOff_box.setItemText(0, _translate("MainWindow", " SORT"))
        self.sortOff_box.setItemText(1, _translate("MainWindow", " OFFICIALID"))
        self.sortOff_box.setItemText(2, _translate("MainWindow", " POSITION"))
        self.sortOff_box.setItemText(3, _translate("MainWindow", " FIRSTNAME"))
        self.sortOff_box.setItemText(4, _translate("MainWindow", " LASTNAME"))
        self.sortOff_box.setItemText(5, _translate("MainWindow", " CONTACT"))
        self.refreshOffiBtn_2.setText(_translate("MainWindow", "Refresh"))
        self.lineEdit_4.setText(_translate("MainWindow", "32"))
        self.label_7.setText(_translate("MainWindow", "About"))
        self.labelDateTime2.setText(_translate("MainWindow", "TextLabel"))

                #CHANGES
        #removed font family(system)
        #removed font family (MS System)
        #addResBtn font sizxe to 12 and bold to false
        #set index 0 hidden when dropped down
        #set addResBtn weight to 75
        #set addCompBtn weight to 75
        #set addOffiBtn weight to 75
        # Apply header style to all tables

        table_style = """
        QHeaderView::section {
        background-color: #f3f6f9;
        color: #333;
        border: none;
        font-weight: 50;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
        text-align: left;
        }
        QHeaderView::section:!first {
        border-top-left-radius: 0px;
        }
        QHeaderView::section:!last {
        border-top-right-radius: 0px;
        }
        """
        
        # table_style stylesheet to header
        self.resident_table.horizontalHeader().setStyleSheet(table_style)
        self.complaint_table.horizontalHeader().setStyleSheet(table_style)
        self.official_table.horizontalHeader().setStyleSheet(table_style) 
        self.pendingComp_table.horizontalHeader().setStyleSheet(table_style)
        
        #disable index 0
        self.sortCases_box.setCurrentIndex(0)
        self.sortCases_box.model().item(0).setEnabled(False)
        self.sortCases_box.view().setRowHidden(0, True)

        self.sortRes_box.setCurrentIndex(0)
        self.sortRes_box.model().item(0).setEnabled(False)
        self.sortRes_box.view().setRowHidden(0, True)

        self.sortComp_box.setCurrentIndex(0) 
        self.sortComp_box.model().item(0).setEnabled(False)
        self.sortComp_box.view().setRowHidden(0, True)

        self.sortOff_box.setCurrentIndex(0)
        self.sortOff_box.model().item(0).setEnabled(False)
        self.sortOff_box.view().setRowHidden(0, True)
        
        OtherBtn_style = """
        QPushButton {
                text-align: left;
                padding: 10px 14px 10px 25px;
                color: white;
                background-color: transparent;
                border: none;
        }
        QPushButton:hover {
                background-color: rgb(0, 0, 77);
        }
        """

        GlossyBlueStyle = """
        QPushButton {
                background-color: qlineargradient(
                        spread:pad, x1:0, y1:0, x2:0, y2:1,
                        stop:0 rgba(100, 149, 255, 255),
                        stop:0.5 rgba(70, 130, 255, 255),
                        stop:1 rgba(30, 60, 200, 255)
                );
                font-size: 14px;
                color: white;
                border-radius: 4px;
                padding: 10px 14px 10px 25px;
                text-align: left;
        }
        """
        self.addResBtn.setStyleSheet(GlossyBlueStyle)
        self.addCompBtn.setStyleSheet(GlossyBlueStyle)
        self.addOffiBtn.setStyleSheet(GlossyBlueStyle)
        self.refreshCasesBtn.setStyleSheet(GlossyBlueStyle)

        #other_btn style
        self.homeBtn.setStyleSheet(OtherBtn_style)
        self.resBtn.setStyleSheet(OtherBtn_style) 
        self.compBtn.setStyleSheet(OtherBtn_style)
        self.offiBtn.setStyleSheet(OtherBtn_style)
        self.exBtn.setStyleSheet(OtherBtn_style)
        self.abtBtn.setStyleSheet(OtherBtn_style)

        def set_active_button(button):
                buttons = [self.homeBtn, self.resBtn, self.compBtn, self.offiBtn, self.exBtn, self.abtBtn]
                activeStyle = GlossyBlueStyle + """
                QPushButton {
                    font-size: 16px; /* Increased font size when active */
                }
                """
                for btn in buttons:
                        btn.setStyleSheet(OtherBtn_style)
                button.setStyleSheet(activeStyle)

        #clicks
        self.homeBtn.clicked.connect(lambda: set_active_button(self.homeBtn))
        self.resBtn.clicked.connect(lambda: set_active_button(self.resBtn))
        self.compBtn.clicked.connect(lambda: set_active_button(self.compBtn))
        self.offiBtn.clicked.connect(lambda: set_active_button(self.offiBtn)) 
        self.exBtn.clicked.connect(lambda: set_active_button(self.exBtn))
        self.abtBtn.clicked.connect(lambda: set_active_button(self.abtBtn))

        self.pendingComp_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.resident_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.complaint_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.official_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)

        #shadow
        for frame in [self.resident_table, self.complaint_table, self.official_table, self.frame_11, self.frame_10, self.frame_9, self.frame_8, self.frame_7, self.frame_13]:
                shadow = QGraphicsDropShadowEffect()
                shadow.setBlurRadius(10)
                shadow.setOffset(2, 2)
                shadow.setColor(QColor(0, 0, 0, 150))
                frame.setGraphicsEffect(shadow)

        #custom drop dowm arrow
        comboBoxStyle = """
            QComboBox {
                background-color: white;
                border: 1px solid rgb(230, 230, 230);
                border-radius: 0px;
            }
            QComboBox::drop-down {
                subcontrol-origin: padding;
                subcontrol-position: top right;
                width: 25px;
                border-left-width: 0px;
                border-top-right-radius: 3px;
                border-bottom-right-radius: 3px;
                background-color: white;
            }

            QComboBox::down-arrow {
                image: url(:/icons/icons/angle-small-down.svg);
                width: 16px;
                height: 16px;
            }
        """

        filterBoxStyle = """
                QComboBox {
                        background-color: white;
                        border: 2px solid rgb(230, 230, 230);
                        border-radius: 10px;
                }
                QComboBox::drop-down {
                        subcontrol-origin: padding;
                        subcontrol-position: top right;
                        width: 25px;
                        border-left-width: 0px;
                        border-top-right-radius: 3px;
                        border-bottom-right-radius: 3px;
                        background-color: white;
                }
                QComboBox::down-arrow {
                        image: url(:/icons/icons/filter.svg);
                        width: 16px;
                        height: 16px;
                }
        """

        self.filterPendComp_box.setStyleSheet(filterBoxStyle)
        #apply to all combo box
        self.sortRes_box.setStyleSheet(comboBoxStyle)
        self.sortComp_box.setStyleSheet(comboBoxStyle)
        self.sortOff_box.setStyleSheet(comboBoxStyle)
        self.sortCases_box.setStyleSheet(comboBoxStyle)
        self.searchbyRes_box.setStyleSheet(comboBoxStyle)
        self.searchbyComp_box.setStyleSheet(comboBoxStyle)
        self.searchbyOff_box.setStyleSheet(comboBoxStyle)


        # Make resident_table items read-only
        self.resident_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        self.pendingComp_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.pendingComp_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.resident_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.resident_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.complaint_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.complaint_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.official_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.official_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)

        self.pendingComp_table.verticalHeader().setVisible(False)
        self.resident_table.verticalHeader().setVisible(False)
        self.complaint_table.verticalHeader().setVisible(False)
        self.official_table.verticalHeader().setVisible(False)