# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addresidentui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addResidentDialog(object):
    def setupUi(self, addResidentDialog):
        addResidentDialog.setObjectName("addResidentDialog")
        addResidentDialog.resize(890, 521)
        addResidentDialog.setStyleSheet("background-color: rgb(0, 0, 25);")
        self.frame = QtWidgets.QFrame(addResidentDialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 851, 481))
        self.frame.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-radius: 13px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 60, 811, 401))
        self.frame_2.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_resident_id = QtWidgets.QLabel(self.frame_2)
        self.label_resident_id.setGeometry(QtCore.QRect(20, 10, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resident_id.setFont(font)
        self.label_resident_id.setStyleSheet("border: 0px")
        self.label_resident_id.setObjectName("label_resident_id")
        self.addresident_residentID_input = QtWidgets.QLineEdit(self.frame_2)
        self.addresident_residentID_input.setGeometry(QtCore.QRect(20, 40, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addresident_residentID_input.setFont(font)
        self.addresident_residentID_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.addresident_residentID_input.setObjectName("addresident_residentID_input")
        self.label_first_name = QtWidgets.QLabel(self.frame_2)
        self.label_first_name.setGeometry(QtCore.QRect(20, 70, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_first_name.setFont(font)
        self.label_first_name.setStyleSheet("border: 0px")
        self.label_first_name.setObjectName("label_first_name")
        self.addresident_firstname_input = QtWidgets.QLineEdit(self.frame_2)
        self.addresident_firstname_input.setGeometry(QtCore.QRect(20, 100, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addresident_firstname_input.setFont(font)
        self.addresident_firstname_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.addresident_firstname_input.setObjectName("addresident_firstname_input")
        self.label_last_name = QtWidgets.QLabel(self.frame_2)
        self.label_last_name.setGeometry(QtCore.QRect(20, 130, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_last_name.setFont(font)
        self.label_last_name.setStyleSheet("border: 0px")
        self.label_last_name.setObjectName("label_last_name")
        self.addresident_lastname_input = QtWidgets.QLineEdit(self.frame_2)
        self.addresident_lastname_input.setGeometry(QtCore.QRect(20, 160, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addresident_lastname_input.setFont(font)
        self.addresident_lastname_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.addresident_lastname_input.setObjectName("addresident_lastname_input")
        self.label_sex = QtWidgets.QLabel(self.frame_2)
        self.label_sex.setGeometry(QtCore.QRect(20, 190, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sex.setFont(font)
        self.label_sex.setStyleSheet("border: 0px")
        self.label_sex.setObjectName("label_sex")
        self.addresident_sex_input = QtWidgets.QComboBox(self.frame_2)
        self.addresident_sex_input.setGeometry(QtCore.QRect(20, 220, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addresident_sex_input.setFont(font)
        self.addresident_sex_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.addresident_sex_input.setObjectName("addresident_sex_input")
        self.addresident_sex_input.addItem("")
        self.addresident_sex_input.addItem("")
        self.label_contact_3 = QtWidgets.QLabel(self.frame_2)
        self.label_contact_3.setGeometry(QtCore.QRect(20, 260, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_contact_3.setFont(font)
        self.label_contact_3.setStyleSheet("border: 0px")
        self.label_contact_3.setObjectName("label_contact_3")
        self.label_dob = QtWidgets.QLabel(self.frame_2)
        self.label_dob.setGeometry(QtCore.QRect(20, 320, 121, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dob.setFont(font)
        self.label_dob.setStyleSheet("border: 0px")
        self.label_dob.setObjectName("label_dob")
        self.addresident_age_input = QtWidgets.QLineEdit(self.frame_2)
        self.addresident_age_input.setGeometry(QtCore.QRect(20, 290, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addresident_age_input.setFont(font)
        self.addresident_age_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.addresident_age_input.setText("")
        self.addresident_age_input.setObjectName("addresident_age_input")
        self.label_contact = QtWidgets.QLabel(self.frame_2)
        self.label_contact.setGeometry(QtCore.QRect(430, 10, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_contact.setFont(font)
        self.label_contact.setStyleSheet("border: 0px")
        self.label_contact.setObjectName("label_contact")
        self.addresident_dob_input = QtWidgets.QDateEdit(self.frame_2)
        self.addresident_dob_input.setGeometry(QtCore.QRect(20, 350, 361, 28))
        font = QtGui.QFont()
        self.addresident_dob_input.setFont(font)
        self.addresident_dob_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.addresident_dob_input.setCalendarPopup(True)
        self.addresident_dob_input.setObjectName("addresident_dob_input")
        self.addresident_contact_input = QtWidgets.QLineEdit(self.frame_2)
        self.addresident_contact_input.setGeometry(QtCore.QRect(430, 40, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addresident_contact_input.setFont(font)
        self.addresident_contact_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.addresident_contact_input.setObjectName("addresident_contact_input")
        self.label_address = QtWidgets.QLabel(self.frame_2)
        self.label_address.setGeometry(QtCore.QRect(430, 70, 161, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_address.setFont(font)
        self.label_address.setStyleSheet("border: 0px")
        self.label_address.setObjectName("label_address")
        self.addresident_address_input = QtWidgets.QTextEdit(self.frame_2)
        self.addresident_address_input.setGeometry(QtCore.QRect(430, 100, 361, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addresident_address_input.setFont(font)
        self.addresident_address_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.addresident_address_input.setObjectName("addresident_address_input")
        self.label_contact_2 = QtWidgets.QLabel(self.frame_2)
        self.label_contact_2.setGeometry(QtCore.QRect(430, 200, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_contact_2.setFont(font)
        self.label_contact_2.setStyleSheet("border: 0px")
        self.label_contact_2.setObjectName("label_contact_2")
        self.addresident_photo_label = QtWidgets.QLabel(self.frame_2)
        self.addresident_photo_label.setGeometry(QtCore.QRect(430, 230, 261, 151))
        self.addresident_photo_label.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addresident_photo_label.setFont(font)
        self.addresident_photo_label.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.addresident_photo_label.setScaledContents(True)
        self.addresident_photo_label.setObjectName("addresident_photo_label")
        self.addresident_photo_button = QtWidgets.QPushButton(self.frame_2)
        self.addresident_photo_button.setGeometry(QtCore.QRect(700, 300, 91, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.addresident_photo_button.setFont(font)
        self.addresident_photo_button.setStyleSheet("border: 1px solid rgb(230, 230, 230);\n"
"")
        self.addresident_photo_button.setObjectName("addresident_photo_button")
        self.addresident_cancel_button = QtWidgets.QPushButton(self.frame)
        self.addresident_cancel_button.setGeometry(QtCore.QRect(720, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.addresident_cancel_button.setFont(font)
        self.addresident_cancel_button.setStyleSheet("background-color: rgb(255, 179, 179);\n"
"border-radius: 10px;\n"
"color: black;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addresident_cancel_button.setIcon(icon)
        self.addresident_cancel_button.setObjectName("addresident_cancel_button")
        self.addresident_addentry_button = QtWidgets.QPushButton(self.frame)
        self.addresident_addentry_button.setGeometry(QtCore.QRect(600, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.addresident_addentry_button.setFont(font)
        self.addresident_addentry_button.setStyleSheet("background-color: rgb(148, 255, 148);\n"
"border-radius: 10px;\n"
"color: black;")
        self.addresident_addentry_button.setObjectName("addresident_addentry_button")

        self.retranslateUi(addResidentDialog)
        QtCore.QMetaObject.connectSlotsByName(addResidentDialog)

    def retranslateUi(self, addResidentDialog):
        _translate = QtCore.QCoreApplication.translate
        addResidentDialog.setWindowTitle(_translate("addResidentDialog", "Add New Resident"))
        self.label_resident_id.setText(_translate("addResidentDialog", "Resident ID:"))
        self.label_first_name.setText(_translate("addResidentDialog", "First Name:"))
        self.label_last_name.setText(_translate("addResidentDialog", "Last Name:"))
        self.label_sex.setText(_translate("addResidentDialog", "Sex:"))
        self.addresident_sex_input.setItemText(0, _translate("addResidentDialog", "Male"))
        self.addresident_sex_input.setItemText(1, _translate("addResidentDialog", "Female"))
        self.label_contact_3.setText(_translate("addResidentDialog", "Age:"))
        self.label_dob.setText(_translate("addResidentDialog", "Date of Birth:"))
        self.label_contact.setText(_translate("addResidentDialog", "Contact:"))
        self.label_address.setText(_translate("addResidentDialog", "Address:"))
        self.addresident_address_input.setHtml(_translate("addResidentDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_contact_2.setText(_translate("addResidentDialog", "Photo Credentials:"))
        self.addresident_photo_label.setText(_translate("addResidentDialog", "No photo selected"))
        self.addresident_photo_button.setText(_translate("addResidentDialog", "Upload"))
        self.addresident_cancel_button.setText(_translate("addResidentDialog", "Cancel"))
        self.addresident_addentry_button.setText(_translate("addResidentDialog", "Add Entry"))
