# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ComplaSys_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt #changes
from resources import resource_qrc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1775, 949)
        MainWindow.setStyleSheet("background-color: rgb(224, 224, 224);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fullMenu = QtWidgets.QWidget(self.centralwidget)
        self.fullMenu.setGeometry(QtCore.QRect(30, 20, 291, 841))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fullMenu.setFont(font)
        self.fullMenu.setStyleSheet("background-color: rgb(242,243,244);\n"
"border-radius: 13px;")
        self.fullMenu.setObjectName("fullMenu")
        self.label_3 = QtWidgets.QLabel(self.fullMenu)
        self.label_3.setGeometry(QtCore.QRect(0, 40, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.homeBtn = QtWidgets.QPushButton(self.fullMenu)
        self.homeBtn.setGeometry(QtCore.QRect(30, 200, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.homeBtn.setFont(font)
        self.homeBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;\n"
"text-align: left;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons-flat/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon)
        self.homeBtn.setObjectName("homeBtn")
        self.resBtn = QtWidgets.QPushButton(self.fullMenu)
        self.resBtn.setGeometry(QtCore.QRect(30, 260, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.resBtn.setFont(font)
        self.resBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;\n"
"text-align: left;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons-flat/users-alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resBtn.setIcon(icon1)
        self.resBtn.setObjectName("resBtn")
        self.compBtn = QtWidgets.QPushButton(self.fullMenu)
        self.compBtn.setGeometry(QtCore.QRect(30, 320, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.compBtn.setFont(font)
        self.compBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;\n"
"text-align: left;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons-flat/document.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.compBtn.setIcon(icon2)
        self.compBtn.setObjectName("compBtn")
        self.offiBtn = QtWidgets.QPushButton(self.fullMenu)
        self.offiBtn.setGeometry(QtCore.QRect(30, 380, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.offiBtn.setFont(font)
        self.offiBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;\n"
"text-align: left;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons-flat/briefcase.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.offiBtn.setIcon(icon3)
        self.offiBtn.setObjectName("offiBtn")
        self.frame = QtWidgets.QFrame(self.fullMenu)
        self.frame.setGeometry(QtCore.QRect(0, 750, 291, 91))
        self.frame.setStyleSheet("background-color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.accBtn = QtWidgets.QPushButton(self.frame)
        self.accBtn.setGeometry(QtCore.QRect(30, 20, 61, 51))
        self.accBtn.setStyleSheet("background-color: white;\n"
"border-radius: 9px;\n"
"border: 2px solid grey;")
        self.accBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons-flat/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accBtn.setIcon(icon4)
        self.accBtn.setObjectName("accBtn")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(100, 30, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 50, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.exBtn = QtWidgets.QPushButton(self.fullMenu)
        self.exBtn.setGeometry(QtCore.QRect(30, 670, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.exBtn.setFont(font)
        self.exBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.exBtn.setObjectName("exBtn")
        self.settBtn = QtWidgets.QPushButton(self.fullMenu)
        self.settBtn.setGeometry(QtCore.QRect(30, 440, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.settBtn.setFont(font)
        self.settBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;\n"
"text-align: left;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons-flat/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settBtn.setIcon(icon5)
        self.settBtn.setObjectName("settBtn")
        self.abtBtn = QtWidgets.QPushButton(self.fullMenu)
        self.abtBtn.setGeometry(QtCore.QRect(30, 500, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.abtBtn.setFont(font)
        self.abtBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;\n"
"text-align: left;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons-flat/interrogation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abtBtn.setIcon(icon6)
        self.abtBtn.setObjectName("abtBtn")
        self.faqBtn = QtWidgets.QPushButton(self.fullMenu)
        self.faqBtn.setGeometry(QtCore.QRect(30, 560, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.faqBtn.setFont(font)
        self.faqBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;\n"
"text-align: left;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons-flat/exclamation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.faqBtn.setIcon(icon7)
        self.faqBtn.setObjectName("faqBtn")
        self.label_4 = QtWidgets.QLabel(self.fullMenu)
        self.label_4.setGeometry(QtCore.QRect(0, 90, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(370, 20, 1381, 851))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color: rgb(242,243,244);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 1431, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.label_7.setObjectName("label_7")
        self.labelDateTime1 = QtWidgets.QLabel(self.page)
        self.labelDateTime1.setGeometry(QtCore.QRect(1200, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDateTime1.setFont(font)
        self.labelDateTime1.setStyleSheet("background-color: white;")
        self.labelDateTime1.setObjectName("labelDateTime1")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 1431, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.label_8.setObjectName("label_8")
        self.resident_table = QtWidgets.QTableWidget(self.page_2)
        self.resident_table.setGeometry(QtCore.QRect(40, 190, 1311, 581))
        self.resident_table.setStyleSheet("background-color: white;\n"
"border-radius: 1px;")
        self.resident_table.setObjectName("resident_table")
        self.resident_table.setColumnCount(7)
        self.resident_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.resident_table.setHorizontalHeaderItem(6, item)
        self.resident_table.horizontalHeader().setStretchLastSection(False)
        self.updResBtn = QtWidgets.QPushButton(self.page_2)
        self.updResBtn.setGeometry(QtCore.QRect(1190, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        self.updResBtn.setFont(font)
        self.updResBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons-flat/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updResBtn.setIcon(icon8)
        self.updResBtn.setObjectName("updResBtn")
        self.delResBtn = QtWidgets.QPushButton(self.page_2)
        self.delResBtn.setGeometry(QtCore.QRect(1070, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        self.delResBtn.setFont(font)
        self.delResBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons-flat/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delResBtn.setIcon(icon9)
        self.delResBtn.setObjectName("delResBtn")
        self.addResBtn = QtWidgets.QPushButton(self.page_2)
        self.addResBtn.setGeometry(QtCore.QRect(1180, 130, 161, 41))
        font = QtGui.QFont()
        font.setBold(False)
        self.addResBtn.setFont(font)
        self.addResBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons-flat/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addResBtn.setIcon(icon10)
        self.addResBtn.setObjectName("addResBtn")
        self.searchRes_line = QtWidgets.QLineEdit(self.page_2)
        self.searchRes_line.setGeometry(QtCore.QRect(30, 120, 451, 51))
        self.searchRes_line.setStyleSheet("background-color: white;\n"
"border-radius: 2px;")
        self.searchRes_line.setObjectName("searchRes_line")
        self.searchResBtn = QtWidgets.QPushButton(self.page_2)
        self.searchResBtn.setGeometry(QtCore.QRect(490, 120, 61, 51))
        self.searchResBtn.setStyleSheet("background-color: white;\n"
"border-radius: 9px;")
        self.searchResBtn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons-flat/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchResBtn.setIcon(icon11)
        self.searchResBtn.setObjectName("searchResBtn")
        self.refreshResBtn = QtWidgets.QPushButton(self.page_2)
        self.refreshResBtn.setGeometry(QtCore.QRect(100, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.refreshResBtn.setFont(font)
        self.refreshResBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.refreshResBtn.setObjectName("refreshResBtn")
        self.saveResBtn = QtWidgets.QPushButton(self.page_2)
        self.saveResBtn.setGeometry(QtCore.QRect(220, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.saveResBtn.setFont(font)
        self.saveResBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.saveResBtn.setObjectName("saveResBtn")
        self.labelDateTime2 = QtWidgets.QLabel(self.page_2)
        self.labelDateTime2.setGeometry(QtCore.QRect(1200, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDateTime2.setFont(font)
        self.labelDateTime2.setStyleSheet("background-color: white;")
        self.labelDateTime2.setObjectName("labelDateTime2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 1431, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.label_9.setObjectName("label_9")
        self.complaint_table = QtWidgets.QTableWidget(self.page_3)
        self.complaint_table.setGeometry(QtCore.QRect(40, 190, 1311, 581))
        self.complaint_table.setStyleSheet("background-color: white;\n"
"border-radius: 1px;")
        self.complaint_table.setObjectName("complaint_table")
        self.complaint_table.setColumnCount(7)
        self.complaint_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaint_table.setHorizontalHeaderItem(6, item)
        self.delCompBtn = QtWidgets.QPushButton(self.page_3)
        self.delCompBtn.setGeometry(QtCore.QRect(1070, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.delCompBtn.setFont(font)
        self.delCompBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.delCompBtn.setIcon(icon9)
        self.delCompBtn.setObjectName("delCompBtn")
        self.updCompBtn = QtWidgets.QPushButton(self.page_3)
        self.updCompBtn.setGeometry(QtCore.QRect(1190, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.updCompBtn.setFont(font)
        self.updCompBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.updCompBtn.setIcon(icon8)
        self.updCompBtn.setObjectName("updCompBtn")
        self.addCompBtn = QtWidgets.QPushButton(self.page_3)
        self.addCompBtn.setGeometry(QtCore.QRect(1180, 130, 161, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.addCompBtn.setFont(font)
        self.addCompBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.addCompBtn.setIcon(icon10)
        self.addCompBtn.setObjectName("addCompBtn")
        self.searchComp_line = QtWidgets.QLineEdit(self.page_3)
        self.searchComp_line.setGeometry(QtCore.QRect(30, 120, 451, 51))
        self.searchComp_line.setStyleSheet("background-color: white;\n"
"border-radius: 2px;")
        self.searchComp_line.setObjectName("searchComp_line")
        self.searchCompBtn = QtWidgets.QPushButton(self.page_3)
        self.searchCompBtn.setGeometry(QtCore.QRect(490, 120, 61, 51))
        self.searchCompBtn.setStyleSheet("background-color: white;\n"
"border-radius: 9px;")
        self.searchCompBtn.setText("")
        self.searchCompBtn.setIcon(icon11)
        self.searchCompBtn.setObjectName("searchCompBtn")
        self.refreshCompBtn = QtWidgets.QPushButton(self.page_3)
        self.refreshCompBtn.setGeometry(QtCore.QRect(100, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.refreshCompBtn.setFont(font)
        self.refreshCompBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.refreshCompBtn.setObjectName("refreshCompBtn")
        self.saveCompBtn = QtWidgets.QPushButton(self.page_3)
        self.saveCompBtn.setGeometry(QtCore.QRect(220, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.saveCompBtn.setFont(font)
        self.saveCompBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.saveCompBtn.setObjectName("saveCompBtn")
        self.labelDateTime3 = QtWidgets.QLabel(self.page_3)
        self.labelDateTime3.setGeometry(QtCore.QRect(1200, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDateTime3.setFont(font)
        self.labelDateTime3.setStyleSheet("background-color: white;")
        self.labelDateTime3.setObjectName("labelDateTime3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_10 = QtWidgets.QLabel(self.page_4)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 1431, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.label_10.setObjectName("label_10")
        self.official_table = QtWidgets.QTableWidget(self.page_4)
        self.official_table.setGeometry(QtCore.QRect(40, 190, 1311, 581))
        self.official_table.setStyleSheet("background-color: white;\n"
"border-radius: 1px;")
        self.official_table.setObjectName("official_table")
        self.official_table.setColumnCount(5)
        self.official_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.official_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.official_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.official_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.official_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.official_table.setHorizontalHeaderItem(4, item)
        self.updOffiBtn = QtWidgets.QPushButton(self.page_4)
        self.updOffiBtn.setGeometry(QtCore.QRect(1190, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.updOffiBtn.setFont(font)
        self.updOffiBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.updOffiBtn.setIcon(icon8)
        self.updOffiBtn.setObjectName("updOffiBtn")
        self.delOffiBtn = QtWidgets.QPushButton(self.page_4)
        self.delOffiBtn.setGeometry(QtCore.QRect(1070, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.delOffiBtn.setFont(font)
        self.delOffiBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.delOffiBtn.setIcon(icon9)
        self.delOffiBtn.setObjectName("delOffiBtn")
        self.addOffiBtn = QtWidgets.QPushButton(self.page_4)
        self.addOffiBtn.setGeometry(QtCore.QRect(1180, 130, 161, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.addOffiBtn.setFont(font)
        self.addOffiBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.addOffiBtn.setIcon(icon10)
        self.addOffiBtn.setObjectName("addOffiBtn")
        self.searchOffi_line = QtWidgets.QLineEdit(self.page_4)
        self.searchOffi_line.setGeometry(QtCore.QRect(30, 120, 451, 51))
        self.searchOffi_line.setStyleSheet("background-color: white;\n"
"border-radius: 2px;")
        self.searchOffi_line.setObjectName("searchOffi_line")
        self.searchOffiBtn = QtWidgets.QPushButton(self.page_4)
        self.searchOffiBtn.setGeometry(QtCore.QRect(490, 120, 61, 51))
        self.searchOffiBtn.setStyleSheet("background-color: white;\n"
"border-radius: 9px;")
        self.searchOffiBtn.setText("")
        self.searchOffiBtn.setIcon(icon11)
        self.searchOffiBtn.setObjectName("searchOffiBtn")
        self.refreshOffiBtn = QtWidgets.QPushButton(self.page_4)
        self.refreshOffiBtn.setGeometry(QtCore.QRect(100, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.refreshOffiBtn.setFont(font)
        self.refreshOffiBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.refreshOffiBtn.setObjectName("refreshOffiBtn")
        self.saveOffiBtn = QtWidgets.QPushButton(self.page_4)
        self.saveOffiBtn.setGeometry(QtCore.QRect(220, 790, 101, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.saveOffiBtn.setFont(font)
        self.saveOffiBtn.setStyleSheet("background-color: white;\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.saveOffiBtn.setObjectName("saveOffiBtn")
        self.labelDateTime4 = QtWidgets.QLabel(self.page_4)
        self.labelDateTime4.setGeometry(QtCore.QRect(1200, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDateTime4.setFont(font)
        self.labelDateTime4.setStyleSheet("background-color: white;")
        self.labelDateTime4.setObjectName("labelDateTime4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_11 = QtWidgets.QLabel(self.page_5)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 1431, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.label_11.setObjectName("label_11")
        self.labelDateTime5 = QtWidgets.QLabel(self.page_5)
        self.labelDateTime5.setGeometry(QtCore.QRect(1200, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDateTime5.setFont(font)
        self.labelDateTime5.setStyleSheet("background-color: white;")
        self.labelDateTime5.setObjectName("labelDateTime5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_12 = QtWidgets.QLabel(self.page_6)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 1431, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.label_12.setObjectName("label_12")
        self.labelDateTime6 = QtWidgets.QLabel(self.page_6)
        self.labelDateTime6.setGeometry(QtCore.QRect(1200, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDateTime6.setFont(font)
        self.labelDateTime6.setStyleSheet("background-color: white;")
        self.labelDateTime6.setObjectName("labelDateTime6")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_13 = QtWidgets.QLabel(self.page_7)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 1431, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.label_13.setObjectName("label_13")
        self.labelDateTime7 = QtWidgets.QLabel(self.page_7)
        self.labelDateTime7.setGeometry(QtCore.QRect(1200, 30, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDateTime7.setFont(font)
        self.labelDateTime7.setStyleSheet("background-color: white;")
        self.labelDateTime7.setObjectName("labelDateTime7")
        self.stackedWidget.addWidget(self.page_7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1775, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "ComplaSys"))
        self.homeBtn.setText(_translate("MainWindow", " Dashboard"))
        self.resBtn.setText(_translate("MainWindow", " Residents"))
        self.compBtn.setText(_translate("MainWindow", " Complaints"))
        self.offiBtn.setText(_translate("MainWindow", " Officials"))
        self.label.setText(_translate("MainWindow", "ADMIN"))
        self.label_2.setText(_translate("MainWindow", "Del Carmen Complaint System"))
        self.exBtn.setText(_translate("MainWindow", "Exit"))
        self.settBtn.setText(_translate("MainWindow", " Settings"))
        self.abtBtn.setText(_translate("MainWindow", " About"))
        self.faqBtn.setText(_translate("MainWindow", " FAQ"))
        self.label_4.setText(_translate("MainWindow", "Del Carmen Complaint System"))
        self.label_7.setText(_translate("MainWindow", "  Dashboard"))
        self.labelDateTime1.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "  Residents"))
        item = self.resident_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "residentID"))
        item = self.resident_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "lastname"))
        item = self.resident_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "sex"))
        item = self.resident_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "birthdate"))
        item = self.resident_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "contact"))
        item = self.resident_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "address"))
        item = self.resident_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "credentials"))
        self.updResBtn.setText(_translate("MainWindow", "Edit"))
        self.delResBtn.setText(_translate("MainWindow", "Delete"))
        self.addResBtn.setText(_translate("MainWindow", "Add Resident"))
        self.searchRes_line.setPlaceholderText(_translate("MainWindow", "Search Residents..."))
        self.refreshResBtn.setText(_translate("MainWindow", "Refresh"))
        self.saveResBtn.setText(_translate("MainWindow", "Save"))
        self.labelDateTime2.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "  Complaints"))
        item = self.complaint_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "complaintID"))
        item = self.complaint_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "residentID"))
        item = self.complaint_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "category"))
        item = self.complaint_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "description"))
        item = self.complaint_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "datetime"))
        item = self.complaint_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "location"))
        item = self.complaint_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "status"))
        self.delCompBtn.setText(_translate("MainWindow", "Delete"))
        self.updCompBtn.setText(_translate("MainWindow", "Edit"))
        self.addCompBtn.setText(_translate("MainWindow", "Add Complaint"))
        self.searchComp_line.setPlaceholderText(_translate("MainWindow", "Search Complaints..."))
        self.refreshCompBtn.setText(_translate("MainWindow", "Refresh"))
        self.saveCompBtn.setText(_translate("MainWindow", "Save"))
        self.labelDateTime3.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "  Officials"))
        item = self.official_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "officialID"))
        item = self.official_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "position"))
        item = self.official_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "firstname"))
        item = self.official_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "lastname"))
        item = self.official_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "contact"))
        self.updOffiBtn.setText(_translate("MainWindow", "Edit"))
        self.delOffiBtn.setText(_translate("MainWindow", "Delete"))
        self.addOffiBtn.setText(_translate("MainWindow", "Add Official"))
        self.searchOffi_line.setPlaceholderText(_translate("MainWindow", "Search Officials..."))
        self.refreshOffiBtn.setText(_translate("MainWindow", "Refresh"))
        self.saveOffiBtn.setText(_translate("MainWindow", "Save"))
        self.labelDateTime4.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "  Settings"))
        self.labelDateTime5.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "  About"))
        self.labelDateTime6.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "  FAQ"))
        self.labelDateTime7.setText(_translate("MainWindow", "TextLabel"))

        #changes (removed sentfotfamily)
        self.resident_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.complaint_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.official_table.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)

        SearchLine_style = """
    QLineEdit {
        background-color: white;
        border-radius: 2px;
        }
    QLineEdit:focus {
    border: 2px solid purple;
        }
"""
        self.searchRes_line.setStyleSheet(SearchLine_style)
        self.searchComp_line.setStyleSheet(SearchLine_style)
        self.searchOffi_line.setStyleSheet(SearchLine_style)

        ExitBtn_style = """
    QPushButton {
        background-color: white;
        border-radius: 9px;
        text-align: center;
    }
    QPushButton:hover {
        background-color: rgb(204, 204, 204);
    }
        QPushButton.active {
        border: 2px solid purple;
    }
"""

        SearchBtn_style = """
    QPushButton {
        background-color: white;
        border-radius: 9px;
    }
    QPushButton:hover {
        background-color: rgb(204, 204, 204);
    }
"""

        OtherBtn_style = """
    QPushButton {
        background-color: white;
        border-radius: 9px;
        border: 2px solid rgb(230, 230, 230);
        text-align: left;
        padding: 10px 14px 10px 25px;
    }
    QPushButton:hover {
        background-color: rgb(204, 204, 204);
    }
        QPushButton.active {
        border: 2px solid purple;
    }
"""
        MainBtn_style = """
    QPushButton {
        background-color: white;
        border: 1px solid grey;
        border-radius: 13px;
    }
    QPushButton:hover {
        background-color: rgb(204, 204, 204);
    }
"""
        SearchLine_style = """
    QLineEdit {
        background-color: white;
        border-radius: 13px;
        border: 1px solid rgb(230, 230, 230);
        }
"""

        AddBtn_style = """
    QPushButton {
        background-color: rgb(223, 212, 244);
        border: 2px solid purple;
        border-radius: 2px;
        color: purple;
        }
"""

        def set_active_button(button):
            buttons = [self.homeBtn, self.resBtn, self.compBtn, self.offiBtn, self.exBtn, self.settBtn, self.abtBtn, self.faqBtn]
            for btn in buttons:
                btn.setStyleSheet(OtherBtn_style)
                button.setStyleSheet(OtherBtn_style + "QPushButton { background-color: rgb(223, 212, 244); color: purple; border: 2px solid purple; font-size: 20px; }")

        self.homeBtn.clicked.connect(lambda: set_active_button(self.homeBtn))
        self.resBtn.clicked.connect(lambda: set_active_button(self.resBtn))
        self.compBtn.clicked.connect(lambda: set_active_button(self.compBtn))
        self.offiBtn.clicked.connect(lambda: set_active_button(self.offiBtn))
        self.exBtn.clicked.connect(lambda: set_active_button(self.exBtn))
        self.settBtn.clicked.connect(lambda: set_active_button(self.settBtn))
        self.abtBtn.clicked.connect(lambda: set_active_button(self.abtBtn))
        self.faqBtn.clicked.connect(lambda: set_active_button(self.faqBtn))

        self.addCompBtn.setStyleSheet(AddBtn_style)
        self.delCompBtn.setStyleSheet(MainBtn_style)
        self.updCompBtn.setStyleSheet(MainBtn_style)
        self.refreshCompBtn.setStyleSheet(MainBtn_style)
        self.saveCompBtn.setStyleSheet(MainBtn_style)
        self.addResBtn.setStyleSheet(AddBtn_style)
        self.delResBtn.setStyleSheet(MainBtn_style)
        self.updResBtn.setStyleSheet(MainBtn_style)
        self.refreshResBtn.setStyleSheet(MainBtn_style)
        self.saveResBtn.setStyleSheet(MainBtn_style)
        self.addOffiBtn.setStyleSheet(AddBtn_style)
        self.delOffiBtn.setStyleSheet(MainBtn_style)
        self.updOffiBtn.setStyleSheet(MainBtn_style)
        self.refreshOffiBtn.setStyleSheet(MainBtn_style)
        self.saveOffiBtn.setStyleSheet(MainBtn_style)

        self.searchResBtn.setStyleSheet(SearchBtn_style)
        self.searchCompBtn.setStyleSheet(SearchBtn_style)
        self.searchOffiBtn.setStyleSheet(SearchBtn_style)

        self.homeBtn.setStyleSheet(OtherBtn_style)
        self.resBtn.setStyleSheet(OtherBtn_style)
        self.compBtn.setStyleSheet(OtherBtn_style)
        self.offiBtn.setStyleSheet(OtherBtn_style)
        self.exBtn.setStyleSheet(ExitBtn_style)
        self.settBtn.setStyleSheet(OtherBtn_style)
        self.abtBtn.setStyleSheet(OtherBtn_style)
        self.faqBtn.setStyleSheet(OtherBtn_style)

        self.searchRes_line.setStyleSheet(SearchLine_style)
        self.searchComp_line.setStyleSheet(SearchLine_style)
        self.searchOffi_line.setStyleSheet(SearchLine_style)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())