# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editofficialui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editOfficialDialog(object):
    def setupUi(self, editOfficialDialog):
        editOfficialDialog.setObjectName("editOfficialDialog")
        editOfficialDialog.resize(510, 429)
        editOfficialDialog.setStyleSheet("background-color: rgb(0, 0, 25);")
        self.frame = QtWidgets.QFrame(editOfficialDialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 471, 391))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 50);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.addofficial_cancel_button = QtWidgets.QPushButton(self.frame)
        self.addofficial_cancel_button.setGeometry(QtCore.QRect(260, 350, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addofficial_cancel_button.setFont(font)
        self.addofficial_cancel_button.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.addofficial_cancel_button.setObjectName("addofficial_cancel_button")
        self.addofficial_save_button = QtWidgets.QPushButton(self.frame)
        self.addofficial_save_button.setGeometry(QtCore.QRect(120, 350, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addofficial_save_button.setFont(font)
        self.addofficial_save_button.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.addofficial_save_button.setObjectName("addofficial_save_button")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 10, 431, 321))
        self.frame_2.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 13px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_resident_id = QtWidgets.QLabel(self.frame_2)
        self.label_resident_id.setGeometry(QtCore.QRect(32, 10, 95, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resident_id.setFont(font)
        self.label_resident_id.setStyleSheet("border: 0px")
        self.label_resident_id.setObjectName("label_resident_id")
        self.editofficial_officialID_input = QtWidgets.QLineEdit(self.frame_2)
        self.editofficial_officialID_input.setGeometry(QtCore.QRect(32, 40, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editofficial_officialID_input.setFont(font)
        self.editofficial_officialID_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.editofficial_officialID_input.setObjectName("editofficial_officialID_input")
        self.label_first_name_2 = QtWidgets.QLabel(self.frame_2)
        self.label_first_name_2.setGeometry(QtCore.QRect(32, 130, 103, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_first_name_2.setFont(font)
        self.label_first_name_2.setStyleSheet("border: 0px")
        self.label_first_name_2.setObjectName("label_first_name_2")
        self.editofficial_firstname_input = QtWidgets.QLineEdit(self.frame_2)
        self.editofficial_firstname_input.setGeometry(QtCore.QRect(32, 160, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editofficial_firstname_input.setFont(font)
        self.editofficial_firstname_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.editofficial_firstname_input.setObjectName("editofficial_firstname_input")
        self.label_last_name = QtWidgets.QLabel(self.frame_2)
        self.label_last_name.setGeometry(QtCore.QRect(32, 190, 102, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_last_name.setFont(font)
        self.label_last_name.setStyleSheet("border: 0px")
        self.label_last_name.setObjectName("label_last_name")
        self.editofficial_lastname_input = QtWidgets.QLineEdit(self.frame_2)
        self.editofficial_lastname_input.setGeometry(QtCore.QRect(32, 220, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editofficial_lastname_input.setFont(font)
        self.editofficial_lastname_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.editofficial_lastname_input.setObjectName("editofficial_lastname_input")
        self.label_contact = QtWidgets.QLabel(self.frame_2)
        self.label_contact.setGeometry(QtCore.QRect(32, 250, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_contact.setFont(font)
        self.label_contact.setStyleSheet("border: 0px")
        self.label_contact.setObjectName("label_contact")
        self.editofficial_contact_input = QtWidgets.QLineEdit(self.frame_2)
        self.editofficial_contact_input.setGeometry(QtCore.QRect(32, 280, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editofficial_contact_input.setFont(font)
        self.editofficial_contact_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.editofficial_contact_input.setObjectName("editofficial_contact_input")
        self.editofficial_position_input = QtWidgets.QComboBox(self.frame_2)
        self.editofficial_position_input.setGeometry(QtCore.QRect(32, 100, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editofficial_position_input.setFont(font)
        self.editofficial_position_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.editofficial_position_input.setObjectName("editofficial_position_input")
        self.editofficial_position_input.addItem("")
        self.editofficial_position_input.addItem("")
        self.editofficial_position_input.addItem("")
        self.editofficial_position_input.addItem("")
        self.editofficial_position_input.addItem("")
        self.editofficial_position_input.addItem("")
        self.editofficial_position_input.addItem("")
        self.label_sex = QtWidgets.QLabel(self.frame_2)
        self.label_sex.setGeometry(QtCore.QRect(32, 70, 77, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sex.setFont(font)
        self.label_sex.setStyleSheet("border: 0px")
        self.label_sex.setObjectName("label_sex")

        self.retranslateUi(editOfficialDialog)
        QtCore.QMetaObject.connectSlotsByName(editOfficialDialog)

    def retranslateUi(self, editOfficialDialog):
        _translate = QtCore.QCoreApplication.translate
        editOfficialDialog.setWindowTitle(_translate("editOfficialDialog", "Edit Official"))
        self.addofficial_cancel_button.setText(_translate("editOfficialDialog", "Cancel"))
        self.addofficial_save_button.setText(_translate("editOfficialDialog", "Edit"))
        self.label_resident_id.setText(_translate("editOfficialDialog", "Official ID:"))
        self.label_first_name_2.setText(_translate("editOfficialDialog", "First Name:"))
        self.label_last_name.setText(_translate("editOfficialDialog", "Last Name:"))
        self.label_contact.setText(_translate("editOfficialDialog", "Contact:"))
        self.editofficial_position_input.setItemText(0, _translate("editOfficialDialog", "Barangay Captain"))
        self.editofficial_position_input.setItemText(1, _translate("editOfficialDialog", "Barangay Councilor"))
        self.editofficial_position_input.setItemText(2, _translate("editOfficialDialog", "SK Offical"))
        self.editofficial_position_input.setItemText(3, _translate("editOfficialDialog", "Barangay Secretary"))
        self.editofficial_position_input.setItemText(4, _translate("editOfficialDialog", "Barangay Treasurer"))
        self.editofficial_position_input.setItemText(5, _translate("editOfficialDialog", "Barangay Health Worker"))
        self.editofficial_position_input.setItemText(6, _translate("editOfficialDialog", "Barangay Tanod"))
        self.label_sex.setText(_translate("editOfficialDialog", "Position:"))
