# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inforesidentui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infoResidentDialog(object):
    def setupUi(self, infoResidentDialog):
        infoResidentDialog.setObjectName("infoResidentDialog")
        infoResidentDialog.resize(890, 521)
        infoResidentDialog.setStyleSheet("background-color: rgb(0, 0, 25);")
        self.frame = QtWidgets.QFrame(infoResidentDialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 851, 481))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 50);\n"
"border-radius: 13px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 60, 811, 401))
        self.frame_2.setStyleSheet("background-color: white;\n"
"border-radius: 13px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_resident_id = QtWidgets.QLabel(self.frame_2)
        self.label_resident_id.setGeometry(QtCore.QRect(20, 10, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resident_id.setFont(font)
        self.label_resident_id.setStyleSheet("border: 0px")
        self.label_resident_id.setObjectName("label_resident_id")
        self.inforesident_residentID_input = QtWidgets.QLineEdit(self.frame_2)
        self.inforesident_residentID_input.setGeometry(QtCore.QRect(20, 40, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inforesident_residentID_input.setFont(font)
        self.inforesident_residentID_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.inforesident_residentID_input.setObjectName("inforesident_residentID_input")
        self.label_first_name = QtWidgets.QLabel(self.frame_2)
        self.label_first_name.setGeometry(QtCore.QRect(20, 70, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_first_name.setFont(font)
        self.label_first_name.setStyleSheet("border: 0px")
        self.label_first_name.setObjectName("label_first_name")
        self.inforesident_firstname_input = QtWidgets.QLineEdit(self.frame_2)
        self.inforesident_firstname_input.setGeometry(QtCore.QRect(20, 100, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inforesident_firstname_input.setFont(font)
        self.inforesident_firstname_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.inforesident_firstname_input.setObjectName("inforesident_firstname_input")
        self.label_last_name = QtWidgets.QLabel(self.frame_2)
        self.label_last_name.setGeometry(QtCore.QRect(20, 130, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_last_name.setFont(font)
        self.label_last_name.setStyleSheet("border: 0px")
        self.label_last_name.setObjectName("label_last_name")
        self.inforesident_lastname_input = QtWidgets.QLineEdit(self.frame_2)
        self.inforesident_lastname_input.setGeometry(QtCore.QRect(20, 160, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inforesident_lastname_input.setFont(font)
        self.inforesident_lastname_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.inforesident_lastname_input.setObjectName("inforesident_lastname_input")
        self.label_sex = QtWidgets.QLabel(self.frame_2)
        self.label_sex.setGeometry(QtCore.QRect(20, 190, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sex.setFont(font)
        self.label_sex.setStyleSheet("border: 0px")
        self.label_sex.setObjectName("label_sex")
        self.inforesident_sex_input = QtWidgets.QComboBox(self.frame_2)
        self.inforesident_sex_input.setGeometry(QtCore.QRect(20, 220, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inforesident_sex_input.setFont(font)
        self.inforesident_sex_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.inforesident_sex_input.setObjectName("inforesident_sex_input")
        self.inforesident_sex_input.addItem("")
        self.inforesident_sex_input.addItem("")
        self.label_contact_3 = QtWidgets.QLabel(self.frame_2)
        self.label_contact_3.setGeometry(QtCore.QRect(20, 260, 131, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_contact_3.setFont(font)
        self.label_contact_3.setStyleSheet("border: 0px")
        self.label_contact_3.setObjectName("label_contact_3")
        self.label_dob = QtWidgets.QLabel(self.frame_2)
        self.label_dob.setGeometry(QtCore.QRect(20, 320, 121, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dob.setFont(font)
        self.label_dob.setStyleSheet("border: 0px")
        self.label_dob.setObjectName("label_dob")
        self.inforesident_age_input = QtWidgets.QLineEdit(self.frame_2)
        self.inforesident_age_input.setGeometry(QtCore.QRect(20, 290, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inforesident_age_input.setFont(font)
        self.inforesident_age_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.inforesident_age_input.setObjectName("inforesident_age_input")
        self.label_contact = QtWidgets.QLabel(self.frame_2)
        self.label_contact.setGeometry(QtCore.QRect(430, 20, 141, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_contact.setFont(font)
        self.label_contact.setStyleSheet("border: 0px")
        self.label_contact.setObjectName("label_contact")
        self.inforesident_dob_input = QtWidgets.QDateEdit(self.frame_2)
        self.inforesident_dob_input.setGeometry(QtCore.QRect(20, 350, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.inforesident_dob_input.setFont(font)
        self.inforesident_dob_input.setStyleSheet("background-color: white;\n"
"font-size: 12px;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.inforesident_dob_input.setCalendarPopup(True)
        self.inforesident_dob_input.setObjectName("inforesident_dob_input")
        self.inforesident_contact_input = QtWidgets.QLineEdit(self.frame_2)
        self.inforesident_contact_input.setGeometry(QtCore.QRect(430, 50, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inforesident_contact_input.setFont(font)
        self.inforesident_contact_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.inforesident_contact_input.setObjectName("inforesident_contact_input")
        self.label_address = QtWidgets.QLabel(self.frame_2)
        self.label_address.setGeometry(QtCore.QRect(430, 90, 161, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_address.setFont(font)
        self.label_address.setStyleSheet("border: 0px")
        self.label_address.setObjectName("label_address")
        self.inforesident_address_input = QtWidgets.QTextEdit(self.frame_2)
        self.inforesident_address_input.setGeometry(QtCore.QRect(430, 120, 361, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inforesident_address_input.setFont(font)
        self.inforesident_address_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 0px;")
        self.inforesident_address_input.setObjectName("inforesident_address_input")
        self.label_contact_2 = QtWidgets.QLabel(self.frame_2)
        self.label_contact_2.setGeometry(QtCore.QRect(430, 220, 201, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_contact_2.setFont(font)
        self.label_contact_2.setStyleSheet("border: 0px")
        self.label_contact_2.setObjectName("label_contact_2")
        self.inforesident_photo_label = QtWidgets.QLabel(self.frame_2)
        self.inforesident_photo_label.setGeometry(QtCore.QRect(430, 250, 241, 131))
        self.inforesident_photo_label.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inforesident_photo_label.setFont(font)
        self.inforesident_photo_label.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 13px;")
        self.inforesident_photo_label.setScaledContents(True)
        self.inforesident_photo_label.setObjectName("inforesident_photo_label")
        self.delResBtn = QtWidgets.QPushButton(self.frame)
        self.delResBtn.setGeometry(QtCore.QRect(720, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.delResBtn.setFont(font)
        self.delResBtn.setStyleSheet("background-color: rgb(255, 179, 179);\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: black;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delResBtn.setIcon(icon)
        self.delResBtn.setObjectName("delResBtn")
        self.updResBtn = QtWidgets.QPushButton(self.frame)
        self.updResBtn.setGeometry(QtCore.QRect(610, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.updResBtn.setFont(font)
        self.updResBtn.setStyleSheet("background-color: rgb(255, 217, 148);\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: black;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updResBtn.setIcon(icon1)
        self.updResBtn.setObjectName("updResBtn")
        self.saveResBtn = QtWidgets.QPushButton(self.frame)
        self.saveResBtn.setGeometry(QtCore.QRect(500, 10, 101, 41))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.saveResBtn.setFont(font)
        self.saveResBtn.setStyleSheet("background-color: rgb(148, 255, 148);\n"
"border: 2px solid rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: black;")
        self.saveResBtn.setObjectName("saveResBtn")

        self.retranslateUi(infoResidentDialog)
        QtCore.QMetaObject.connectSlotsByName(infoResidentDialog)

    def retranslateUi(self, infoResidentDialog):
        _translate = QtCore.QCoreApplication.translate
        infoResidentDialog.setWindowTitle(_translate("infoResidentDialog", "Resident Information"))
        self.label_resident_id.setText(_translate("infoResidentDialog", "Resident ID:"))
        self.label_first_name.setText(_translate("infoResidentDialog", "First Name:"))
        self.label_last_name.setText(_translate("infoResidentDialog", "Last Name:"))
        self.label_sex.setText(_translate("infoResidentDialog", "Sex:"))
        self.inforesident_sex_input.setItemText(0, _translate("infoResidentDialog", "Male"))
        self.inforesident_sex_input.setItemText(1, _translate("infoResidentDialog", "Female"))
        self.label_contact_3.setText(_translate("infoResidentDialog", "Age:"))
        self.label_dob.setText(_translate("infoResidentDialog", "Date of Birth:"))
        self.label_contact.setText(_translate("infoResidentDialog", "Contact:"))
        self.label_address.setText(_translate("infoResidentDialog", "Address:"))
        self.label_contact_2.setText(_translate("infoResidentDialog", "Photo Credentials:"))
        self.inforesident_photo_label.setText(_translate("infoResidentDialog", "No photo selected"))
        self.delResBtn.setText(_translate("infoResidentDialog", "Delete"))
        self.updResBtn.setText(_translate("infoResidentDialog", "Edit"))
        self.saveResBtn.setText(_translate("infoResidentDialog", "Save"))
