# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infoofficialui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_infoOfficialDialog(object):
    def setupUi(self, infoOfficialDialog):
        infoOfficialDialog.setObjectName("infoOfficialDialog")
        infoOfficialDialog.resize(513, 541)
        infoOfficialDialog.setStyleSheet("background-color: rgb(0, 0, 25);")
        self.frame = QtWidgets.QFrame(infoOfficialDialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 471, 501))
        self.frame.setStyleSheet("background-color: rgb(245, 245, 245);\n"
"border-radius: 13px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 60, 431, 431))
        self.frame_2.setStyleSheet("background-color: white;\n"
"border: 1px solid rgb(230, 230, 230);\n"
"border-radius: 13px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_resident_id = QtWidgets.QLabel(self.frame_2)
        self.label_resident_id.setGeometry(QtCore.QRect(32, 10, 95, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resident_id.setFont(font)
        self.label_resident_id.setStyleSheet("border: 0px")
        self.label_resident_id.setObjectName("label_resident_id")
        self.infoofficial_officialID_input = QtWidgets.QLineEdit(self.frame_2)
        self.infoofficial_officialID_input.setGeometry(QtCore.QRect(32, 40, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.infoofficial_officialID_input.setFont(font)
        self.infoofficial_officialID_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.infoofficial_officialID_input.setObjectName("infoofficial_officialID_input")
        self.label_first_name_2 = QtWidgets.QLabel(self.frame_2)
        self.label_first_name_2.setGeometry(QtCore.QRect(32, 130, 103, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_first_name_2.setFont(font)
        self.label_first_name_2.setStyleSheet("border: 0px")
        self.label_first_name_2.setObjectName("label_first_name_2")
        self.infoofficial_firstname_input = QtWidgets.QLineEdit(self.frame_2)
        self.infoofficial_firstname_input.setGeometry(QtCore.QRect(32, 160, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.infoofficial_firstname_input.setFont(font)
        self.infoofficial_firstname_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.infoofficial_firstname_input.setObjectName("infoofficial_firstname_input")
        self.label_last_name = QtWidgets.QLabel(self.frame_2)
        self.label_last_name.setGeometry(QtCore.QRect(32, 190, 102, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_last_name.setFont(font)
        self.label_last_name.setStyleSheet("border: 0px")
        self.label_last_name.setObjectName("label_last_name")
        self.infoofficial_lastname_input = QtWidgets.QLineEdit(self.frame_2)
        self.infoofficial_lastname_input.setGeometry(QtCore.QRect(32, 220, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.infoofficial_lastname_input.setFont(font)
        self.infoofficial_lastname_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.infoofficial_lastname_input.setObjectName("infoofficial_lastname_input")
        self.label_contact = QtWidgets.QLabel(self.frame_2)
        self.label_contact.setGeometry(QtCore.QRect(32, 250, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_contact.setFont(font)
        self.label_contact.setStyleSheet("border: 0px")
        self.label_contact.setObjectName("label_contact")
        self.infoofficial_contact_input = QtWidgets.QLineEdit(self.frame_2)
        self.infoofficial_contact_input.setGeometry(QtCore.QRect(32, 280, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.infoofficial_contact_input.setFont(font)
        self.infoofficial_contact_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.infoofficial_contact_input.setObjectName("infoofficial_contact_input")
        self.infoofficial_position_input = QtWidgets.QComboBox(self.frame_2)
        self.infoofficial_position_input.setGeometry(QtCore.QRect(32, 100, 361, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.infoofficial_position_input.setFont(font)
        self.infoofficial_position_input.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.infoofficial_position_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.infoofficial_position_input.setObjectName("infoofficial_position_input")
        self.infoofficial_position_input.addItem("")
        self.infoofficial_position_input.addItem("")
        self.infoofficial_position_input.addItem("")
        self.infoofficial_position_input.addItem("")
        self.infoofficial_position_input.addItem("")
        self.infoofficial_position_input.addItem("")
        self.infoofficial_position_input.addItem("")
        self.label_sex = QtWidgets.QLabel(self.frame_2)
        self.label_sex.setGeometry(QtCore.QRect(32, 70, 77, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sex.setFont(font)
        self.label_sex.setStyleSheet("border: 0px")
        self.label_sex.setObjectName("label_sex")
        self.label_address_3 = QtWidgets.QLabel(self.frame_2)
        self.label_address_3.setGeometry(QtCore.QRect(30, 310, 107, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_address_3.setFont(font)
        self.label_address_3.setStyleSheet("border: 0px")
        self.label_address_3.setObjectName("label_address_3")
        self.infoofficial_caseshandled_input = QtWidgets.QTextEdit(self.frame_2)
        self.infoofficial_caseshandled_input.setGeometry(QtCore.QRect(30, 340, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.infoofficial_caseshandled_input.setFont(font)
        self.infoofficial_caseshandled_input.setStyleSheet("background-color: white;\n"
"border: 1px solid grey;\n"
"border-radius: 4px;")
        self.infoofficial_caseshandled_input.setObjectName("infoofficial_caseshandled_input")
        self.saveOffiBtn = QtWidgets.QPushButton(self.frame)
        self.saveOffiBtn.setGeometry(QtCore.QRect(140, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.saveOffiBtn.setFont(font)
        self.saveOffiBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveOffiBtn.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border-radius: 10px;\n"
"color: black;")
        self.saveOffiBtn.setObjectName("saveOffiBtn")
        self.updOffiBtn = QtWidgets.QPushButton(self.frame)
        self.updOffiBtn.setGeometry(QtCore.QRect(240, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.updOffiBtn.setFont(font)
        self.updOffiBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updOffiBtn.setStyleSheet("background-color: rgb(255, 217, 148);\n"
"border-radius: 10px;\n"
"color: black;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updOffiBtn.setIcon(icon)
        self.updOffiBtn.setObjectName("updOffiBtn")
        self.delOffiBtn = QtWidgets.QPushButton(self.frame)
        self.delOffiBtn.setGeometry(QtCore.QRect(340, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setBold(False)
        font.setWeight(50)
        self.delOffiBtn.setFont(font)
        self.delOffiBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delOffiBtn.setStyleSheet("background-color: rgb(255, 179, 179);\n"
"border-radius: 10px;\n"
"color: black;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delOffiBtn.setIcon(icon1)
        self.delOffiBtn.setObjectName("delOffiBtn")

        self.retranslateUi(infoOfficialDialog)
        QtCore.QMetaObject.connectSlotsByName(infoOfficialDialog)

    def retranslateUi(self, infoOfficialDialog):
        _translate = QtCore.QCoreApplication.translate
        infoOfficialDialog.setWindowTitle(_translate("infoOfficialDialog", "Official Information"))
        self.label_resident_id.setText(_translate("infoOfficialDialog", "Official ID:"))
        self.infoofficial_officialID_input.setPlaceholderText(_translate("infoOfficialDialog", " Ex: 0001-2025"))
        self.label_first_name_2.setText(_translate("infoOfficialDialog", "First Name:"))
        self.infoofficial_firstname_input.setPlaceholderText(_translate("infoOfficialDialog", " Ex: Jane"))
        self.label_last_name.setText(_translate("infoOfficialDialog", "Last Name:"))
        self.infoofficial_lastname_input.setPlaceholderText(_translate("infoOfficialDialog", " Ex: Doe"))
        self.label_contact.setText(_translate("infoOfficialDialog", "Contact:"))
        self.infoofficial_contact_input.setPlaceholderText(_translate("infoOfficialDialog", " Ex: 09987654321"))
        self.infoofficial_position_input.setItemText(0, _translate("infoOfficialDialog", "Barangay Captain"))
        self.infoofficial_position_input.setItemText(1, _translate("infoOfficialDialog", "Barangay Councilor"))
        self.infoofficial_position_input.setItemText(2, _translate("infoOfficialDialog", "SK Offical"))
        self.infoofficial_position_input.setItemText(3, _translate("infoOfficialDialog", "Barangay Secretary"))
        self.infoofficial_position_input.setItemText(4, _translate("infoOfficialDialog", "Barangay Treasurer"))
        self.infoofficial_position_input.setItemText(5, _translate("infoOfficialDialog", "Barangay Health Worker"))
        self.infoofficial_position_input.setItemText(6, _translate("infoOfficialDialog", "Barangay Tanod"))
        self.label_sex.setText(_translate("infoOfficialDialog", "Position:"))
        self.label_address_3.setText(_translate("infoOfficialDialog", "Cases Handled:"))
        self.infoofficial_caseshandled_input.setHtml(_translate("infoOfficialDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.infoofficial_caseshandled_input.setPlaceholderText(_translate("infoOfficialDialog", " Please provide if applicable"))
        self.saveOffiBtn.setText(_translate("infoOfficialDialog", "Save"))
        self.updOffiBtn.setText(_translate("infoOfficialDialog", "Edit"))
        self.delOffiBtn.setText(_translate("infoOfficialDialog", "Delete"))
